name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build APK
      run: |
        sudo apt update
        sudo apt install unzip -y
        unzip PuzzleCoach.zip -d PuzzleCoach
        cd PuzzleCoach
        ./gradlew assembleDebug
    - name: Upload APK
      - uses: actions/upload-artifact@v4
      with:
        name: PuzzleCoach-apk
        path: app/build/outputs/apk/debug/app-debug.apk
